delete_ebs_volumes lambda now preserves volumes that have an associated, active PersistentVolume.
CMS-Enterprise/batcave-tf-misc-modules pull request #2
Opened 2022-08-31 20:14 UTC by sflanker

Fixes [BATIAI-835](https://jiraent.cms.gov/browse/BATIAI-835)

2022-08-31 20:16 UTC, sflanker commented
Making this a draft while I test it as a lambda. FWIW you can now run this locally with:

```
python3 main.py
```

or

```
python3 main.py --dry-run
```

2022-09-08 12:56 UTC, bushong1 commented on delete_ebs_volumes/lambda.tf
> +  triggers = {
Great work on the triggers

2022-09-08 12:57 UTC, bushong1 commented on delete_ebs_volumes/lambda.tf
> +    build_log = fileexists("${path.module}/python/build.log") ? filemd5("${path.module}/python/build.log") : timestamp()
Should we commit the buildlog because of this?

2022-09-08 13:09 UTC, dgwhited requested changes

2022-09-08 13:09 UTC, dgwhited commented on delete_ebs_volumes/lambda.tf
> +  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
Lets instead add the required permissions to the IAM policy we are creating, rather than using an AWS managed policy.

```    
       {
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:AssignPrivateIpAddresses",
                "ec2:UnassignPrivateIpAddresses"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
```
These actions technically allow this lambda to delete ENIs that it doesn't use, but we are only implementing this in dev/test.

AWS has a [history](https://www.cloudvulndb.org/results?q=AWS%20managed%20policies) of overprovisioning and lack of change management for their managed policies.

2022-09-08 17:41 UTC, sflanker commented on delete_ebs_volumes/lambda.tf
> +  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
And there I went assuming AWS would be following best practices with their managed policies 🤦‍♂️

2022-09-08 17:43 UTC, sflanker commented on delete_ebs_volumes/lambda.tf
> +    build_log = fileexists("${path.module}/python/build.log") ? filemd5("${path.module}/python/build.log") : timestamp()
I did consider this, and I'm still open to it, however:

```
$ du -d 1 -h
111M	./build
$ find build | wc -l
5111
```
100 Mb and 5K files seems like a lot to shove into git.

2022-09-08 18:36 UTC, sflanker commented on delete_ebs_volumes/lambda.tf
> +  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
done

2022-09-08 18:40 UTC, dgwhited approved these changes

2022-09-12 21:33 UTC, merged